name: softgraph
services:

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    restart: always
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - /$HOME/.softgraph/postgres/data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/00-init-db.sql
      - ./postgres/dump-demo.sql:/docker-entrypoint-initdb.d/01-dump-demo.sql
    environment:
      - POSTGRES_PASSWORD=${SOFTGRAPH_PG_PWD:-softgraph}
      - POSTGRES_USER=softgraph
      - POSTGRES_DB=softgraph
    networks:
      - spring-postgres

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      additional_contexts:
        sb: ..
    ports:
      - 8080:8080
    environment:
      - SOFTGRAPH_API_KEY=${SOFTGRAPH_API_KEY:-default}
      - SOFTGRAPH_PG_PWD=${SOFTGRAPH_PG_PWD:-softgraph}
    networks:
      - spring-postgres
    depends_on:
      - postgres

networks:
  spring-postgres:
